* Novo web
** como fago cos textos?
*** tenho um document store
**** guarda blobs keyed by filename (hash, actually)
**** S3 em production
**** in-mem em development?
*** tenho umha base de dados
Liga hashes de blobs a arquivos.
**** Datomic Cloud em production
**** In-mem em development
     Pode realmente ser in-mem?  Sempre que se poida fazer datomic.client com ela está bem.
*** Procura?  Indexing?
No servidor web tenho todo cacheado em memória.
** seguinte task
*** Quando clicamos "aplicar" ou "salvar", salvamos o texto
**** que schema?
***** temos first-class representation de comarcas
****** e despois :comarca/quem-somos?
Co texto?  Ou algo máis?
Ou first-class representation de secçons?  Mais entom como ligamos umha com outra?
Nom: a first class representation da secçom é o keyword :semente.comarca/quem-somos
**** onde guardamos o schema?
Fai-nos falta um schema e um data-0 etc.
**** como lhe passamos ao app os credenciais para anovar datomic etc?
Mirar onde os tenho.  Passá-los em env vars, é claro.
Ver documentaçom sobre isso
*** Sacamos o texto de Quem Somos de datomic
*** O formatting de /quill é o dumha página de nacional
**** fonte deja vu, com Ubuntu para headers, etc.
*** /quill é inicializado ao conteudo de Quem Somos
**** que obtemos do web
***** co default "(texto nom encontrado)"
** images
*** detectamos re de image codificada como base64
*** extraemos a image e calculamos o sha
*** se nom temos já esse sha guardado, guardamo-lo no servidor (ou na DB?)
**** tem que ser na DB; nom podemos perder dados
*** mudamos o tag para apontar ao sha
*** no servidor sabemos servir esses shas directamente de datomic (com cache)
** como editar "páginas gerais"
É quill potente abondo? Se nom, outra opçom pode ser dar a opçom de editar raw HTML.

Podo provar com quill; sempre estamos a tempo!

Empregar quill para começar, mais pre-estilá-lo como corresponde a páginas da
Semente e limitar formatos etc.
** estrutura
*** comum
**** possível elemento sobre a barra para anúncios
***** como decidimos quando está ativado?
****** fazer algumha funçom no site de gestom para isso
 Selecciona qual é o texto e onde liga.
**** ligaçons às secçons
***** quem somos / princípios / história / contato
 Página estática. Editável por gente?
*** nacional
**** banner
**** novas da associaçom nacional
**** página principal
Feita a mam, a partir de:
***** texto a destacar (possibly nil)
***** image a destacar (sempre algumha)
***** novas nacional (um par delas)
***** novas de comarcas (interleaved)
***** Ligaçom máis... (pega 9 novas novas e acrescenta-as)
**** quem somos
Página geral
**** princípios
Página geral
**** história
Página geral
**** recursos
Página geral
**** contato
     Página geral
**** associa-te
Formuĺário: feito a mam
*** em cada comarca hai
**** principal
Feita a mam, a partir dos últimos Novas e Dia a Dia
**** quem somos
**** o centro
Página geral
**** dia a dia
Crónicas do que se passa nas aulas.
**** novas
Som novas do centro e a associaçom: eventos. etc.
**** cursos e acampamentos
É parte de "novas" ou outra secçom?
**** contato
Dados de contato do centro e de nacional.  Página geral.
**** associa-te
Leva à mesma secçom em nacional, ou temos associa-te ainda para cada centro?
**** nacional
Simplesmente leva a semente.gal.
** friend
*** coordinaçom com Sente?
Quem di que queira usar Sente at all?  Quem di que precise coordinar com friend?
One thing at a time.

Se vou usar ajax at all, vou usar sente?  Seguramente si.

Vou usar ajax at all? Nom tenho ningum use case in mind, mais parece um pouco
temerário fechar-me essa porta.

Mais estou realmente fechando-me essa porta?  Porque nom poderia furrular com
Sente igual?
*** roles
**** admin 
***** cria utentes, dá e tira roles de admin-* e editora-*
**** admin-nacional
***** pode criar utentes, dar/tirar rol de admin-nacional editora-nacional
**** admin-(compos|lugo|vigo|trasancos)
***** pode criar utentes, dar/tirar rol de (admin|editora)-(compos|lugo|vigo|trasancos)
**** editora-nacional
**** editora-(compos|lugo|trasancos|vigo)
** representaçom de texto/ediçom
html para current version -- noHistory
guardar edits em quill delta format
ou guardar todo em html?
** mudanças estruturais
*** elemento opcional por riba/baixo do cabeçalho
*** como flowam as movidas?
**** comprovar navegadores estreitos, mobile
** começar já coa lógica?
Os dados vam, é claro, em datomic.  O conteúdo estático das secçons vai em
Markdown ou html directamente em git.  Como assigno classes a movidas markdown?
Em markdown tenho full html, assi que podo assignar class e id.  Mais quero?
Provavelmente nom, provavelmente markdown seja melhor só para cousas que nom
precisem um tratamento especial de CSS.

Ou procurar um editor de markdown pola web?

https://github.com/benhowell/reagent-quill seems to be the ticket.

*** schema para dados
**** secçons
***** módulos com código específico
***** vam em .cljc ou html ou quil -- nada de markdown, sorry.
***** gardados em git
**** conteúdos
***** gardados em datomic
***** markdown
** procurar em página
Brute force search of all current text?
** issues
*** x quando entro texto na caixa de procura
Ver de eliminá-lo
