* Novo web
** representaçom de texto/ediçom
html para current version -- noHistory
guardar edits em quill delta format
** arquitetura
Passar de diferenciar com umha variável de entorno dev vs prod.  Ter modo dev,
que chama endpoint /dev, e desabilitá-lo se estamos em produçom. Ou ter toggle
específico para isto.
*** um endpoint para cada secçom
Nom quero um SPA.
**** refactorando elementos comuns a comum.cljc
** tasks
*** extraer markup a outro ns .cljc
**** em development, importá-lo desde cljs para live reloading
***** por enquanto, preocupar-me só com development
**** em production, serví-lo desde clj
*** centralizar/unificar css
**** development vs production
***** development
Aqui quero feedback rápido. Quero poder manter umha janela aberta em todo
momento e ver as mudanças sem hit refresh.

Factor out movidas a .cljc? e carregar desde diferentes partes. Markup podo
lê-lo com rum, sem problema. CSS podo injectá-lo directamente ou salvá-lo a um
.css. Qual fazer pode depender de

- Support de boot para watch certain files and output garden
- Capacidade de switchear injeçom entre development e runtime

Se a opçom de boot estiver disponível, seguramente seja máis fácil.

***** production
**** mesmo nos logos?
***** tentar
*** meter num grid
**** fazer um elemento centrado que contenha todo
** estrutura
*** possível elemento sobre a barra para anúncios
**** como decidimos quando está ativado?
***** fazer algumha funçom no site de gestom para isso
Selecciona qual é o texto e onde liga.
*** ligaçons às secçons
**** quem somos / princípios / história / contato
Página estática. Editável por gente?
**** recursos?
Suponho que será página estática tamém.
**** associa-te?
*** cores?
**** com gimp extraer os valores do doc de fernando
*** fontes?
**** manter Ubuntu enquanto nom tenha confirmaçom da nova
Acho que el dizia que nom estava em webfonts, mais está (assegurar-me desde
outro SO).
** elementos a acrescentar
*** jeito de meter arquivos
**** markdown
***** guardar como markdown, ou como html?
****** o segundo permite layouts máis específicos
****** o primeiro fai máis fácil editar
**** meter datomic já, para guardá-los!
** mudanças estruturais
*** elemento opcional por riba/baixo do cabeçalho
*** que fontes temos?
*** como flowam as movidas?
** outras mudanças
*** CSS grid
*** reagent?
Se me quero passar a Posh ou re-frame é importante. Mais nom permite rendering
server-side?

Tamém podo experimentar com ir fazendo eu algo parecido a re-frame. Talvez com
subscripçons específicas a datomic?
** começar já coa lógica?
Os dados vam, é claro, em datomic.  O conteúdo estático das secçons vai em
Markdown ou html directamente em git.  Como assigno classes a movidas markdown?
Em markdown tenho full html, assi que podo assignar class e id.  Mais quero?
Provavelmente nom, provavelmente markdown seja melhor só para cousas que nom
precisem um tratamento especial de CSS.

Ou procurar um editor de markdown pola web?

https://github.com/benhowell/reagent-quill seems to be the ticket.

*** schema para dados
**** secçons
***** módulos com código específico
***** vam em .cljc ou html ou quil -- nada de markdown, sorry.
***** gardados em git
**** conteúdos
***** gardados em datomic
***** markdown
** issues
*** x quando entro texto na caixa de procura
**** eliminá-lo ou estilá-lo?
